// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Songbird.Web.CompiledModels
{
    [DbContext(typeof(SongbirdContext))]
    public partial class SongbirdContextModel : RuntimeModel
    {
        static SongbirdContextModel()
        {
            var model = new SongbirdContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static SongbirdContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
