// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Songbird.Web.CompiledModels
{
    partial class SongbirdContextModel
    {
        partial void Initialize()
        {
            var fikaMatchUser = FikaMatchUserEntityType.Create(this);
            var binaryFile = BinaryFileEntityType.Create(this);
            var customer = CustomerEntityType.Create(this);
            var fikaMatch = FikaMatchEntityType.Create(this);
            var fikaSchedule = FikaScheduleEntityType.Create(this);
            var lunchGame = LunchGameEntityType.Create(this);
            var lunchGamingAttendance = LunchGamingAttendanceEntityType.Create(this);
            var lunchGamingDate = LunchGamingDateEntityType.Create(this);
            var project = ProjectEntityType.Create(this);
            var user = UserEntityType.Create(this);
            var userPhoto = UserPhotoEntityType.Create(this);

            FikaMatchUserEntityType.CreateForeignKey1(fikaMatchUser, fikaMatch);
            FikaMatchUserEntityType.CreateForeignKey2(fikaMatchUser, user);
            CustomerEntityType.CreateForeignKey1(customer, binaryFile);
            FikaMatchEntityType.CreateForeignKey1(fikaMatch, fikaSchedule);
            LunchGameEntityType.CreateForeignKey1(lunchGame, binaryFile);
            LunchGamingAttendanceEntityType.CreateForeignKey1(lunchGamingAttendance, lunchGamingDate);
            LunchGamingAttendanceEntityType.CreateForeignKey2(lunchGamingAttendance, lunchGamingDate);
            LunchGamingAttendanceEntityType.CreateForeignKey3(lunchGamingAttendance, user);
            LunchGamingDateEntityType.CreateForeignKey1(lunchGamingDate, lunchGame);
            ProjectEntityType.CreateForeignKey1(project, customer);
            ProjectEntityType.CreateForeignKey2(project, customer);
            ProjectEntityType.CreateForeignKey3(project, binaryFile);

            FikaMatchEntityType.CreateSkipNavigation1(fikaMatch, user, fikaMatchUser);
            UserEntityType.CreateSkipNavigation1(user, fikaMatch, fikaMatchUser);

            FikaMatchUserEntityType.CreateAnnotations(fikaMatchUser);
            BinaryFileEntityType.CreateAnnotations(binaryFile);
            CustomerEntityType.CreateAnnotations(customer);
            FikaMatchEntityType.CreateAnnotations(fikaMatch);
            FikaScheduleEntityType.CreateAnnotations(fikaSchedule);
            LunchGameEntityType.CreateAnnotations(lunchGame);
            LunchGamingAttendanceEntityType.CreateAnnotations(lunchGamingAttendance);
            LunchGamingDateEntityType.CreateAnnotations(lunchGamingDate);
            ProjectEntityType.CreateAnnotations(project);
            UserEntityType.CreateAnnotations(user);
            UserPhotoEntityType.CreateAnnotations(userPhoto);

            AddAnnotation("ProductVersion", "6.0.0-preview.5.21301.9");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
