variables:
  AZP_CACHING_TAR: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
  IS_MAIN: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

trigger:
  branches:
    include:
    - '*'

stages:
  - stage: Build
    jobs:
    - job:
      pool:
        vmImage: windows-latest
      displayName: Build thing one
      steps:
        - task: CmdLine@2
          displayName: Thing one
          inputs:
            script: 'echo "Thing one"'
    - job:
      pool:
        vmImage: windows-latest
      displayName: Build thing two
      steps:
        - task: CmdLine@2
          displayName: Thing two
          inputs:
            script: 'echo "Thing two"'

  - template: azure-pipelines-deploy-template.yaml
    parameters:
      environments:
        - name: dev
          branch: develop
        - name: prod
          branch: main
