variables:
  AZP_CACHING_TAR: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
  IS_MAIN: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

trigger:
  branches:
    include:
    - '*'

stages:
  - stage: Build
    jobs:
    - job:
      pool:
        vmImage: windows-latest
      displayName: Build thing one
      steps:
        - task: CmdLine@2
          displayName: Deploy branch ${{ environment.branch }} to environment ${{ environment.name }}
          inputs:
            script: 'echo "Deploy branch ${{ environment.branch }} to environment ${{ environment.name }}'
    - job:
      pool:
        vmImage: windows-latest
      displayName: Build thing two
      steps:
        - task: CmdLine@2
          displayName: Deploy branch ${{ environment.branch }} to environment ${{ environment.name }}
          inputs:
            script: 'echo "Deploy branch ${{ environment.branch }} to environment ${{ environment.name }}'

  - stage: Deploy
    jobs:
      - job: deploy
        pool:
          vmImage: windows-latest
        steps:

        - template: deploy.yml
          parameters:
            environments:
              develop:
                name: dev
                branch: develop

