variables:
  AZP_CACHING_TAR: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
  IS_MAIN: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  AZ_SUBSCRIPTION: 'XLENT Norr (e78adb91-7ca9-42a5-aa40-2d5dd4326c33)'

trigger:
  branches:
    include:
    - '*'

stages:
  - stage: build
    displayName: Build projects
    jobs:
    - job:
      pool:
        vmImage: windows-latest
      displayName: Build thing one
      steps:
        - task: CmdLine@2
          displayName: Thing one
          inputs:
            script: 'echo "Thing one"'
    - job:
      pool:
        vmImage: windows-latest
      displayName: Build thing two
      steps:
        - task: CmdLine@2
          displayName: Thing two
          inputs:
            script: 'echo "Thing two"'

  - template: azure-pipelines-deploy-template.yaml
    parameters:
      environments:
        - name: Development
          branch: develop
          appName: songbird-dev
          subscription: $(AZ_SUBSCRIPTION)
        - name: Production
          branch: main
          appName: songbird-prod
          subscription: $(AZ_SUBSCRIPTION)
